sudo: false
language: node_js
node_js:
  - "8"
  - "lts/*"
matrix:
  include:
    - node_js: "lts/*"
      env: TEST_SUITE=standard
  include:
    - node_js: "lts/*"
      env: TEST_SUITE=coverage
env:
  - TEST_SUITE=unit
script: npm run-script $TEST_SUITE
